### PR TITLE
Integrated the model using flask

### PR DESCRIPTION
**Pull request by gokhalevedant06**

### CODE REVIEW

**Review by Nitesh-thapliyal — COMMENTED** [review]
Can you share the Screenshots  of the web app which show its working, it will be helpful

**Comment by gokhalevedant06** [comment]
image
image

**Comment by gokhalevedant06** [comment]
Hi @Nitesh-thapliyal, You have added the wrong tags to the repo. Could you please change them and also review my PR

**Comment by Nitesh-thapliyal** [comment]
> Hi @Nitesh-thapliyal, You have added the wrong tags to the repo. Could you please change them and also review my PR
Wrong Tags?? @gokhalevedant06

**Comment by gokhalevedant06** [comment]
> > Hi @Nitesh-thapliyal, You have added the wrong tags to the repo. Could you please change them and also review my PR
> > Wrong Tags?? @gokhalevedant06

Spelling of Hacktoberfest is wrong in the tag, resulting the repo to be excluded from hacktobetfest

**Comment by Nitesh-thapliyal** [comment]
Great work btw!

**Comment by gokhalevedant06** [comment]
> Great work btw!

Thank You!

**Comment by Nitesh-thapliyal** [comment]
> > > Hi @Nitesh-thapliyal, You have added the wrong tags to the repo. Could you please change them and also review my PR
> > > Wrong Tags?? @gokhalevedant06
> 
> Spelling of Hacktoberfest is wrong in the tag, resulting the repo to be excluded from hacktobetfest
Thanks for letting me know, I have corrected the typo before merging the PR ✨

**Pull request merged**
